services:
  redis:
    image: redis/redis-stack:latest
    container_name: pmea-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data: