consumer:
  queue_size: 1000
email:
  imap_host: "imap.gmail.com"
  imap_port: 993
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  use_ssl: true
  mailbox: "INBOX"

  # Important: for gmail - enable 2fa and use app password.
  # See: https://myaccount.google.com/u/1/apppasswords
  username: "username@gmail.com"
  password: "your-password"

  # RFC 2177 recommends break and restart IDLE every 29 minutes to keep NATs happy.
  idle_timeout: 1740
  reconnect_delay: 5

llm:
  api_key: "your-api-key"
  model_name: "gemini-2.0-flash"
  temperature: 0.4

# Set log file and custom level if needed.
# logging:
#   level: "INFO"
#   file: "pmea.log"